spring.application.name=2526II_INT3202E_2 Project
app.admin-secret=123456789
spring.datasource.url=jdbc:mysql://mysql-12f2da8b-shopvn.c.aivencloud.com:19080/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_fW2_UtW_z4YfQfyVrLG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
